/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Btn_startSample_aliases.h"
#include "Btn_startSample.h"
#include "ADC.h"
#include "UART.h"
#include "ADC_in_aliases.h"
#include "ADC_in.h"
#include "isr_adc.h"
#include "LED_red_aliases.h"
#include "LED_red.h"
#include "LED_yellow_aliases.h"
#include "LED_yellow.h"
#include "LED_green_aliases.h"
#include "LED_green.h"
#include "DAC_out_aliases.h"
#include "DAC_out.h"
#include "DAC.h"
#include "isr_btn.h"
#include "isr_uart.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "UART_IntClock.h"
#include "DAC_DacClk.h"
#include "DAC_Wave1_DMA_dma.h"
#include "DAC_Wave2_DMA_dma.h"
#include "DAC_VDAC8.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

